spring.application.name=sporty
score.service.protocol=http
score.service.host=score-service
score.service.port=4000
kafka.score.update.topic=score-updates
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

score.service.retry.max-attempts=3
score.service.retry.initial-backoff=1000
score.service.retry.multiplier=2.0
score.service.retry.max-backoff=10000
